#!/bin/bash

# ============================================================================
# scripts/service/install.sh - Install PixEagle service CLI wrapper
# ============================================================================
# Installs /usr/local/bin/pixeagle-service that points to scripts/service/cli.sh
# in this repository checkout.
# ============================================================================

set -euo pipefail

INSTALL_DIR="/usr/local/bin"
SERVICE_COMMAND="pixeagle-service"
INSTALL_PATH="$INSTALL_DIR/$SERVICE_COMMAND"
SERVICE_FILE="/etc/systemd/system/pixeagle.service"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CLI_SCRIPT="$PROJECT_ROOT/scripts/service/cli.sh"
UTILS_SCRIPT="$PROJECT_ROOT/scripts/service/utils.sh"
RUN_SCRIPT="$PROJECT_ROOT/scripts/service/run.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

print_status() {
    local status="$1"
    local message="$2"

    case "$status" in
        "info")    echo -e "${BLUE}[*] $message${NC}" ;;
        "success") echo -e "${GREEN}[OK] $message${NC}" ;;
        "warning") echo -e "${YELLOW}[WARN] $message${NC}" ;;
        "error")   echo -e "${RED}[ERROR] $message${NC}" ;;
        "process") echo -e "${CYAN}[*] $message${NC}" ;;
        *)         echo "$message" ;;
    esac
}

show_help() {
    cat <<'EOF'
Usage: sudo bash scripts/service/install.sh [uninstall]

Commands:
  (no args)  Install pixeagle-service wrapper command
  uninstall  Remove wrapper command and remove pixeagle.service unit
  help       Show this help message
EOF
}

require_root() {
    if [ "$EUID" -ne 0 ]; then
        print_status "error" "Run as root: sudo bash scripts/service/install.sh"
        exit 1
    fi
}

validate_environment() {
    if [ "$(uname -s)" != "Linux" ]; then
        print_status "error" "This installer supports Linux only"
        exit 1
    fi

    if ! command -v systemctl >/dev/null 2>&1; then
        print_status "error" "systemd/systemctl is required"
        exit 1
    fi

    if ! command -v tmux >/dev/null 2>&1; then
        print_status "warning" "tmux is not installed; install it before starting PixEagle service"
    fi
}

validate_project_files() {
    local required=(
        "$CLI_SCRIPT"
        "$UTILS_SCRIPT"
        "$RUN_SCRIPT"
        "$PROJECT_ROOT/scripts/run.sh"
        "$PROJECT_ROOT/scripts/stop.sh"
    )

    local file
    for file in "${required[@]}"; do
        if [ ! -f "$file" ]; then
            print_status "error" "Required file missing: $file"
            exit 1
        fi
    done
}

install_wrapper() {
    print_status "process" "Installing $INSTALL_PATH"
    mkdir -p "$INSTALL_DIR"

    cat > "$INSTALL_PATH" <<EOF
#!/bin/bash
# Auto-generated by scripts/service/install.sh
export PIXEAGLE_INSTALL_DIR="$PROJECT_ROOT"
exec bash "\$PIXEAGLE_INSTALL_DIR/scripts/service/cli.sh" "\$@"
EOF

    chmod 0755 "$INSTALL_PATH"
    chmod 0755 "$CLI_SCRIPT" "$UTILS_SCRIPT" "$RUN_SCRIPT"
    chmod 0755 "$PROJECT_ROOT/scripts/run.sh" "$PROJECT_ROOT/scripts/stop.sh"

    print_status "success" "Installed command: $INSTALL_PATH"
}

uninstall_service() {
    print_status "process" "Removing PixEagle service management"

    if systemctl is-active --quiet pixeagle.service; then
        systemctl stop pixeagle.service || true
    fi

    if systemctl is-enabled --quiet pixeagle.service; then
        systemctl disable pixeagle.service || true
    fi

    if [ -f "$SERVICE_FILE" ]; then
        rm -f "$SERVICE_FILE"
        systemctl daemon-reload
        print_status "success" "Removed service file: $SERVICE_FILE"
    fi

    if [ -f "$INSTALL_PATH" ]; then
        rm -f "$INSTALL_PATH"
        print_status "success" "Removed command: $INSTALL_PATH"
    fi
}

show_completion() {
    echo
    print_status "success" "PixEagle service command installed successfully"
    print_status "info" "Use: pixeagle-service help"
    print_status "info" "Enable auto-start: sudo pixeagle-service enable"
    print_status "info" "Status: pixeagle-service status"
    echo
}

main() {
    case "${1:-}" in
        uninstall|remove)
            require_root
            uninstall_service
            exit 0
            ;;
        help|--help|-h)
            show_help
            exit 0
            ;;
    esac

    require_root
    validate_environment
    validate_project_files
    install_wrapper
    show_completion
}

main "$@"
