#!/bin/bash

# ============================================================================
# scripts/service/install.sh - Install PixEagle standalone service controls
# ============================================================================
# Installs a managed unit without changing boot policy, plus
# /usr/local/bin/pixeagle-service pointing to this repository checkout.
# ============================================================================

set -euo pipefail

INSTALL_DIR="/usr/local/bin"
SERVICE_COMMAND="pixeagle-service"
INSTALL_PATH="$INSTALL_DIR/$SERVICE_COMMAND"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CLI_SCRIPT="$PROJECT_ROOT/scripts/service/cli.sh"
UTILS_SCRIPT="$PROJECT_ROOT/scripts/service/utils.sh"
RUN_SCRIPT="$PROJECT_ROOT/scripts/service/run.sh"
OWNERSHIP_HELPER="$PROJECT_ROOT/scripts/lib/runtime_ownership.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

print_status() {
    local status="$1"
    local message="$2"

    case "$status" in
        "info")    echo -e "${BLUE}[*] $message${NC}" ;;
        "success") echo -e "${GREEN}[OK] $message${NC}" ;;
        "warning") echo -e "${YELLOW}[WARN] $message${NC}" ;;
        "error")   echo -e "${RED}[ERROR] $message${NC}" ;;
        "process") echo -e "${CYAN}[*] $message${NC}" ;;
        *)         echo "$message" ;;
    esac
}

show_help() {
    cat <<'EOF'
Usage: sudo bash scripts/service/install.sh [uninstall]

Commands:
  (no args)  Install/refresh controls; preserve runtime and boot policy
  uninstall  Remove wrapper command and remove pixeagle.service unit
  help       Show this help message

Note: If PixEagle is managed by an external platform (e.g., ARK-OS),
      the platform handles service lifecycle. This installer is only
      needed for standalone deployments.
EOF
}

require_root() {
    if [ "$EUID" -ne 0 ]; then
        print_status "error" "Run as root: sudo bash scripts/service/install.sh"
        exit 1
    fi
}

validate_environment() {
    if [ "$(uname -s)" != "Linux" ]; then
        print_status "error" "This installer supports Linux only"
        exit 1
    fi

    if ! command -v systemctl >/dev/null 2>&1; then
        print_status "error" "systemd/systemctl is required"
        exit 1
    fi

    if ! command -v tmux >/dev/null 2>&1; then
        print_status "warning" "tmux is not installed; install it before starting PixEagle service"
    fi
}

validate_wrapper_generation_values() {
    [[ "$PROJECT_ROOT" == /* ]] || {
        print_status "error" "PixEagle install path must be absolute"
        exit 1
    }
    case "$PROJECT_ROOT" in
        *[[:space:]%\"\\]*|*$'\n'*|*$'\r'*)
            print_status "error" "PixEagle service paths cannot contain whitespace, quotes, backslashes, or percent specifiers"
            exit 1
            ;;
    esac
}

validate_project_files() {
    local required=(
        "$CLI_SCRIPT"
        "$UTILS_SCRIPT"
        "$RUN_SCRIPT"
        "$PROJECT_ROOT/scripts/run.sh"
        "$PROJECT_ROOT/scripts/stop.sh"
        "$OWNERSHIP_HELPER"
    )

    local file
    for file in "${required[@]}"; do
        if [ ! -f "$file" ]; then
            print_status "error" "Required file missing: $file"
            exit 1
        fi
    done

    # The systemd unit executes this script directly.  Its executable bit is
    # part of the reviewed checkout contract; do not repair tracked source
    # modes in place because that makes the updater report a false local edit.
    if [ ! -x "$RUN_SCRIPT" ]; then
        print_status "error" "Service launcher is not executable: $RUN_SCRIPT"
        print_status "note" "Restore the reviewed checkout before installing the service"
        exit 1
    fi

    validate_wrapper_generation_values
}

install_wrapper() {
    print_status "process" "Installing $INSTALL_PATH"
    mkdir -p "$INSTALL_DIR"

    cat > "$INSTALL_PATH" <<EOF
#!/bin/bash
# Auto-generated by scripts/service/install.sh
export PIXEAGLE_INSTALL_DIR="$PROJECT_ROOT"
exec bash "\$PIXEAGLE_INSTALL_DIR/scripts/service/cli.sh" "\$@"
EOF

    # Only the generated wrapper is mutable installation output.  All source
    # scripts retain the modes recorded by Git so setup never dirties a
    # tracked checkout during an update or service repair.
    chmod 0755 "$INSTALL_PATH"

    print_status "success" "Installed command: $INSTALL_PATH"
}

uninstall_service() {
    print_status "process" "Removing PixEagle service management"

    # Use the same tri-state, postcondition-checked removal contract as the
    # service CLI. Query failures must never be interpreted as "not running."
    if ! source "$UTILS_SCRIPT"; then
        print_status "error" "Could not load the service removal contract"
        return 1
    fi
    remove_service || return 1

    if [[ -e "$INSTALL_PATH" || -L "$INSTALL_PATH" ]]; then
        if [[ ! -f "$INSTALL_PATH" || -L "$INSTALL_PATH" ]]; then
            print_status "error" "Refusing unsafe service command path: $INSTALL_PATH"
            return 1
        fi
        rm -f -- "$INSTALL_PATH"
        print_status "success" "Removed command: $INSTALL_PATH"
    fi
}

show_completion() {
    echo
    print_status "success" "PixEagle service controls installed"
    print_status "info" "Start now: pixeagle-service start"
    print_status "info" "Boot auto-start: sudo pixeagle-service enable | disable"
    print_status "info" "More commands: pixeagle-service help"
    echo
}

main() {
    case "${1:-}" in
        uninstall|remove)
            require_root
            uninstall_service
            exit $?
            ;;
        help|--help|-h)
            show_help
            exit 0
            ;;
    esac

    require_root
    validate_environment
    validate_project_files

    # Publish the unit first so a failed unit validation cannot replace a
    # previously working wrapper with one that points to unusable controls.
    # Installing the unit does not start it or change its existing boot policy.
    # shellcheck source=scripts/service/utils.sh
    source "$UTILS_SCRIPT"
    detect_service_user
    refuse_external_user_service_conflict "$SERVICE_USER"
    install_service_unit
    install_wrapper
    show_completion
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
