#!/usr/bin/env python3
"""Validate and fingerprint the complete OpenCV provider in the active venv."""

from __future__ import annotations

import base64
import hashlib
import importlib.metadata as metadata
import json
import os
import re
import stat
import sys
from pathlib import Path, PurePosixPath


SUPPORTED_WHEEL_OWNERS = {
    "opencv-contrib-python",
    "opencv-contrib-python-headless",
}
KNOWN_OPENCV_DISTRIBUTIONS = SUPPORTED_WHEEL_OWNERS | {
    "opencv-python",
    "opencv-python-headless",
}
MAX_PROVIDER_FILES = 20_000
MAX_PROVIDER_BYTES = 2_000_000_000


def normalized_distribution_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def sha256_file(path: Path) -> tuple[str, int]:
    before = path.stat()
    if not stat.S_ISREG(before.st_mode):
        raise RuntimeError(f"OpenCV provider entry is not a regular file: {path}")
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            size += len(chunk)
            digest.update(chunk)
    after = path.stat()
    if size != before.st_size or (before.st_dev, before.st_ino, before.st_mtime_ns) != (
        after.st_dev,
        after.st_ino,
        after.st_mtime_ns,
    ):
        raise RuntimeError(f"OpenCV provider file changed while hashing: {path}")
    return digest.hexdigest(), size


def file_evidence(path: Path, environment: Path) -> dict[str, object]:
    if path.is_symlink():
        raise RuntimeError(f"wheel-owned OpenCV path is a symbolic link: {path}")
    resolved = path.resolve(strict=True)
    if not resolved.is_relative_to(environment):
        raise RuntimeError(f"OpenCV provider path escapes the selected venv: {path}")
    digest, size = sha256_file(resolved)
    return {"path": str(resolved), "size": size, "sha256": digest}


def build_feature_enabled(build_information: str, feature: str) -> bool:
    return (
        re.search(
            rf"^\s*{re.escape(feature)}\s*:\s*YES\b",
            build_information,
            flags=re.IGNORECASE | re.MULTILINE,
        )
        is not None
    )


def discover_opencv_distributions() -> list[metadata.Distribution]:
    owners: list[metadata.Distribution] = []
    names: set[str] = set()
    for distribution in metadata.distributions():
        files = distribution.files or []
        claims_cv2 = any(
            PurePosixPath(str(package_path)).parts[:1] == ("cv2",)
            for package_path in files
        )
        raw_name = distribution.metadata.get("Name") or ""
        name = normalized_distribution_name(raw_name)
        if name not in KNOWN_OPENCV_DISTRIBUTIONS and not claims_cv2:
            continue
        if not name or name in names:
            raise RuntimeError(f"ambiguous OpenCV distribution metadata owner: {raw_name!r}")
        names.add(name)
        owners.append(distribution)
    return owners


def record_digest(package_path: metadata.PackagePath) -> tuple[str, str] | None:
    value = package_path.hash
    if value is None:
        return None
    return value.mode, value.value.rstrip("=")


def verify_wheel_owner(
    distribution: metadata.Distribution,
    module_path: Path,
    environment: Path,
) -> tuple[str, dict[str, object], list[dict[str, object]]]:
    raw_name = distribution.metadata.get("Name") or ""
    name = normalized_distribution_name(raw_name)
    if name not in SUPPORTED_WHEEL_OWNERS:
        raise RuntimeError(
            f"PixEagle requires one contrib wheel as the sole OpenCV owner; found {raw_name!r}"
        )
    files = distribution.files
    if not files:
        raise RuntimeError(f"OpenCV wheel owner has no RECORD inventory: {raw_name}")
    if len(files) > MAX_PROVIDER_FILES:
        raise RuntimeError("OpenCV wheel RECORD exceeds the provider file bound")

    record_paths: set[Path] = set()
    evidence: list[dict[str, object]] = []
    total_size = 0
    record_file_seen = False
    module_owned = False
    for package_path in sorted(files, key=str):
        if str(package_path).endswith(".pyc"):
            # Bytecode is generated by the interpreter and is not provider input.
            continue
        candidate = Path(distribution.locate_file(package_path))
        if candidate.is_symlink():
            raise RuntimeError(f"wheel-owned OpenCV path is a symbolic link: {candidate}")
        resolved = candidate.resolve(strict=True)
        if not resolved.is_relative_to(environment):
            raise RuntimeError(f"wheel RECORD path escapes the selected venv: {candidate}")
        item = file_evidence(candidate, environment)
        total_size += int(item["size"])
        if total_size > MAX_PROVIDER_BYTES:
            raise RuntimeError("OpenCV wheel provider exceeds the fingerprint byte bound")
        record_paths.add(resolved)
        module_owned = module_owned or resolved == module_path

        expected = record_digest(package_path)
        is_record = str(package_path).endswith(".dist-info/RECORD")
        if expected is None:
            if not is_record:
                raise RuntimeError(f"wheel RECORD omitted a digest for provider file: {package_path}")
            record_file_seen = True
        else:
            mode, encoded = expected
            if mode != "sha256":
                raise RuntimeError(f"unsupported wheel RECORD digest for {package_path}: {mode}")
            actual = base64.urlsafe_b64encode(
                bytes.fromhex(str(item["sha256"]))
            ).decode("ascii").rstrip("=")
            if actual != encoded:
                raise RuntimeError(f"wheel RECORD digest mismatch: {package_path}")
        evidence.append(item)

    if not record_file_seen:
        raise RuntimeError("OpenCV wheel owner has no unhashed RECORD self-entry")
    if not module_owned:
        raise RuntimeError("loaded cv2 module is not owned by the sole wheel RECORD")

    cv2_root = module_path.parent
    for candidate in cv2_root.rglob("*"):
        if candidate.is_symlink():
            raise RuntimeError(f"symbolic-link overlay exists in cv2 package: {candidate}")
        if not candidate.is_file() or candidate.suffix == ".pyc":
            continue
        resolved = candidate.resolve(strict=True)
        if resolved not in record_paths:
            raise RuntimeError(f"unowned overlay exists in cv2 package: {candidate}")

    owner_evidence = {
        "name": name,
        "version": distribution.version,
        "record_file_count": len(evidence),
        "record_total_bytes": total_size,
        "record_verified": True,
    }
    return name, owner_evidence, evidence


def walk_source_provider(environment: Path, module_path: Path) -> list[dict[str, object]]:
    roots = [module_path.parent]
    patterns = (
        "lib/libopencv*",
        "include/opencv4",
        "share/opencv4",
        "share/OpenCV",
        "share/licenses/opencv4",
        "lib/cmake/opencv4",
        "lib/pkgconfig/opencv4.pc",
        "bin/opencv_*",
    )
    for pattern in patterns:
        roots.extend(sorted(environment.glob(pattern)))

    evidence: list[dict[str, object]] = []
    seen: set[tuple[int, int, str]] = set()
    total_size = 0

    def add(path: Path) -> None:
        nonlocal total_size
        metadata_value = path.lstat()
        relative = path.relative_to(environment).as_posix()
        if stat.S_ISLNK(metadata_value.st_mode):
            resolved = path.resolve(strict=True)
            if not resolved.is_relative_to(environment):
                raise RuntimeError(f"source OpenCV symlink escapes the selected venv: {path}")
            if not resolved.is_file():
                raise RuntimeError(
                    f"source OpenCV symlink must resolve to a regular provider file: {path}"
                )
            key = (metadata_value.st_dev, metadata_value.st_ino, relative)
            if key in seen:
                return
            seen.add(key)
            digest, size = sha256_file(resolved)
            total_size += size
            if len(evidence) >= MAX_PROVIDER_FILES or total_size > MAX_PROVIDER_BYTES:
                raise RuntimeError("source OpenCV provider exceeds fingerprint bounds")
            evidence.append(
                {
                    "path": str(path),
                    "type": "symlink",
                    "target": os.readlink(path),
                    "resolved_target": str(resolved),
                    "target_size": size,
                    "target_sha256": digest,
                }
            )
            return
        if not stat.S_ISREG(metadata_value.st_mode):
            return
        resolved = path.resolve(strict=True)
        if not resolved.is_relative_to(environment):
            raise RuntimeError(f"source OpenCV file escapes the selected venv: {path}")
        key = (metadata_value.st_dev, metadata_value.st_ino, relative)
        if key in seen:
            return
        seen.add(key)
        digest, size = sha256_file(path)
        total_size += size
        if len(evidence) >= MAX_PROVIDER_FILES or total_size > MAX_PROVIDER_BYTES:
            raise RuntimeError("source OpenCV provider exceeds fingerprint bounds")
        evidence.append({"path": str(path), "size": size, "sha256": digest, "type": "file"})

    for root in roots:
        if root.is_symlink() or root.is_file():
            add(root)
        elif root.is_dir():
            for candidate in sorted(root.rglob("*"), key=lambda item: item.as_posix()):
                add(candidate)
    if not evidence:
        raise RuntimeError("source OpenCV provider did not expose fingerprintable files")
    return evidence


def main() -> int:
    try:
        import cv2
    except Exception as exc:
        raise SystemExit(f"OpenCV import failed: {type(exc).__name__}: {exc}") from exc

    environment = Path(sys.prefix).resolve(strict=True)
    module_path = Path(cv2.__file__).resolve(strict=True)
    if not module_path.is_relative_to(environment):
        raise SystemExit(
            f"OpenCV module is outside the selected virtual environment: {module_path}"
        )

    build_information = cv2.getBuildInformation()
    gstreamer = build_feature_enabled(build_information, "GStreamer")
    ffmpeg = build_feature_enabled(build_information, "FFMPEG")
    if not ffmpeg:
        raise SystemExit("OpenCV FFmpeg support is unavailable")

    legacy = getattr(cv2, "legacy", None)
    tracker_apis: dict[str, bool] = {}
    for name in ("TrackerCSRT_create", "TrackerKCF_create"):
        tracker_apis[name] = callable(getattr(cv2, name, None)) or callable(
            getattr(legacy, name, None)
        )
    if not all(tracker_apis.values()):
        raise SystemExit(f"OpenCV contrib tracker APIs are missing: {tracker_apis}")

    try:
        owners = discover_opencv_distributions()
        if len(owners) > 1:
            names = [item.metadata.get("Name") or "<unnamed>" for item in owners]
            raise RuntimeError(f"multiple OpenCV distribution owners detected: {names}")
        if owners:
            owner_name, owner_evidence, provider_files = verify_wheel_owner(
                owners[0], module_path, environment
            )
            provider_kind = "managed_wheel"
            distribution_owners: dict[str, object] = {owner_name: owner_evidence}
        elif gstreamer:
            provider_kind = "source_gstreamer"
            distribution_owners = {}
            provider_files = walk_source_provider(environment, module_path)
        else:
            raise RuntimeError(
                "OpenCV has no verified wheel owner and no GStreamer source-build marker"
            )
    except (OSError, RuntimeError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc

    print(
        json.dumps(
            {
                "version": cv2.__version__,
                "module_file": str(module_path),
                "provider_kind": provider_kind,
                "gstreamer": gstreamer,
                "ffmpeg": ffmpeg,
                "build_information_sha256": hashlib.sha256(
                    build_information.encode()
                ).hexdigest(),
                "tracker_apis": tracker_apis,
                "distribution_owners": distribution_owners,
                "fingerprinted_files": provider_files,
                "fingerprint_scope": (
                    "the complete verified wheel RECORD, or the complete cv2/source-native "
                    "OpenCV layout inside the selected venv"
                ),
            },
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
