# ==============================================================================
# Configuration File for Application
# ==============================================================================

# ==============================================================================
# Video Input Configuration
# ==============================================================================
VideoSource:
  # Type of video source to use.
  # Options: 'VIDEO_FILE', 'USB_CAMERA', 'RTSP_STREAM', 'UDP_STREAM', 'HTTP_STREAM', 'CSI_CAMERA'
  VIDEO_SOURCE_TYPE: USB_CAMERA
  # Path to video file if VIDEO_SOURCE_TYPE is 'VIDEO_FILE'
  VIDEO_FILE_PATH: resources/test4.mp4
  # Camera index for 'USB_CAMERA' (0 for default webcam)
  CAMERA_INDEX: 0
  # RTSP stream URL if VIDEO_SOURCE_TYPE is 'RTSP_STREAM'
  RTSP_URL: rtsp://192.168.0.108:554/stream=0
  # UDP stream URL if VIDEO_SOURCE_TYPE is 'UDP_STREAM'
  UDP_URL: udp://172.21.144.1:5000
  # HTTP stream URL if VIDEO_SOURCE_TYPE is 'HTTP_STREAM'
  HTTP_URL: http://172.21.144.1:8100
  # CSI camera sensor ID if VIDEO_SOURCE_TYPE is 'CSI_CAMERA'
  CSI_SENSOR_ID: 0  # Typically 0 for the first camera

# ==============================================================================
# Camera Configuration
# ==============================================================================
Camera:
  # Number of frames to store in memory
  STORE_LAST_FRAMES: 100
  # Default frames per second for streaming and recording
  DEFAULT_FPS: 30
  # CSI camera settings
  CSI_WIDTH: 1280
  CSI_HEIGHT: 720
  CSI_FRAMERATE: 30
  CSI_FLIP_METHOD: 0  # 0 - None (default), 1 - Rotate 90° CW, etc.

# ==============================================================================
# Telemetry Configuration
# ==============================================================================
Telemetry:
  # Enable or disable telemetry data
  ENABLE_TELEMETRY: true
  # Rate at which telemetry data is sent (Hz)
  TELEMETRY_SEND_RATE: 2
  # Flask endpoint for telemetry data
  TELEMETRY_FLASK_ENDPOINT: /telemetry
  # UDP streaming settings
  ENABLE_UDP_STREAM: false
  UDP_HOST: 127.0.0.1
  UDP_PORT: 5550
  # WebSocket settings
  WEBSOCK_HOST: 127.0.0.1
  WEBSOCK_PORT: 5551
  # Enable follower telemetry data
  ENABLE_FOLLOWER_TELEMETRY: true

# ==============================================================================
# Streaming Configuration
# ==============================================================================
Streaming:
  # Enable or disable video streaming
  ENABLE_STREAMING: true
  # HTTP streaming settings
  HTTP_STREAM_HOST: 0.0.0.0
  HTTP_STREAM_PORT: 5077
  # Stream quality settings
  STREAM_WIDTH: 1920
  STREAM_HEIGHT: 1080
  STREAM_QUALITY: 100  # JPEG quality (0-100)
  STREAM_FPS: 30
  # Stream processed frame with OSD if true, raw frame if false
  STREAM_PROCESSED_OSD: true

# ==============================================================================
# PX4 MAVSDK Configuration
# ==============================================================================
PX4:
  # Use external MAVSDK server
  EXTERNAL_MAVSDK_SERVER: true
  # System address for connecting to PX4 (e.g., 'udp://:14540') For real companion computer set to 127.0.0.1, For WSL:172.21.148.30 (your WSL IP)
  SYSTEM_ADDRESS: udp://127.0.0.1:14540

# ==============================================================================
# Frame and Estimation Configuration
# ==============================================================================
FrameEstimation:
  # Video frame settings
  FRAME_TITLE: Video
  DEFAULT_FPS: 30
  STORE_LAST_FRAMES: 5
  SHOW_VIDEO_WINDOW: false  # Set to true for debugging
  # Estimator settings
  USE_ESTIMATOR: true
  ESTIMATOR_HISTORY_LENGTH: 5
  ESTIMATOR_ENABLED: true
  ESTIMATOR_TYPE: Kalman  # Or "None" to disable the estimator
  # Estimator parameters
  ESTIMATOR_PROCESS_NOISE_VARIANCE: 10.0  # For acceleration uncertainties
  ESTIMATOR_MEASUREMENT_NOISE_VARIANCE: 1.0  # To trust measurements more
  ESTIMATOR_INITIAL_STATE_COVARIANCE: [5, 5, 50, 50, 100, 100]  # x, y, dx, dy, ddx, ddy
  # Estimator usage
  USE_ESTIMATOR_FOR_FOLLOWING: true
  # Visualization colors
  ESTIMATED_POSITION_COLOR: [255, 0, 0]  # Blue when tracking is successful
  ESTIMATION_ONLY_COLOR: [0, 165, 255]  # Orange when in estimation-only mode

# ==============================================================================
# Frame Preprocessing Configuration
# ==============================================================================
FramePreprocessor:
  # Enable or disable preprocessing
  ENABLE_PREPROCESSING: false
  # Preprocessing techniques
  PREPROCESSING_USE_BLUR: true
  PREPROCESSING_BLUR_KERNEL_SIZE: 5  # Must be an odd number
  PREPROCESSING_USE_MEDIAN_BLUR: false
  PREPROCESSING_MEDIAN_BLUR_KERNEL_SIZE: 5  # Must be an odd number
  PREPROCESSING_USE_CLAHE: true
  PREPROCESSING_CLAHE_CLIP_LIMIT: 2.0
  PREPROCESSING_CLAHE_TILE_GRID_SIZE: 8  # Typically between 1 and 10
  # Color space options: 'BGR', 'GRAY', 'HSV', 'LAB'
  PREPROCESSING_COLOR_SPACE: BGR

# ==============================================================================
# Segmentation Configuration
# ==============================================================================
Segmentation:
  # Available segmentation algorithms
  SEGMENTATION_ALGORITHMS: ['GrabCut', 'Watershed', 'yolov8s-seg', 'yolov8n-oiv7', 'yolov8s-obb']
  # Default segmentation algorithm to use
  DEFAULT_SEGMENTATION_ALGORITHM: yolo/yolov8n-oiv7
  # Use segmentation results for tracking
  USE_SEGMENTATION_FOR_TRACKING: true

# ==============================================================================
# Detector Configuration
# ==============================================================================
Detector:
  # Enable or disable the detector
  USE_DETECTOR: true
  # Template matching settings
  TEMPLATE_UPDATE_INTERVAL: 10  # Update template every N frames
  AUTO_REDETECT: true
  DETECTION_ALGORITHM: TemplateMatching
  TEMPLATE_MATCHING_METHOD: TM_CCOEFF_NORMED
  DEFAULT_FEATURE_EXTRACTION_ALGORITHM: ORB
  # Template matching parameters
  TEMPLATE_APPEARANCE_LEARNING_RATE: 0.002
  TEMPLATE_MATCHING_SCALES: [0.95, 1.0, 1.05]
  APPEARANCE_CONFIDENCE_THRESHOLD: 0.7
  TEMPLATE_MATCHING_THRESHOLD: 0.8
  # Tracker confidence threshold for updating the template
  TRACKER_CONFIDENCE_THRESHOLD_FOR_TEMPLATE_UPDATE: 0.8
  # Redetection parameters
  REDETECTION_SEARCH_RADIUS: 300  # Adjust based on estimator uncertainty
  MIN_SEARCH_RADIUS: 50  # Minimum search radius in pixels
  UNCERTAINTY_SCALE_FACTOR: 2.0  # Scales uncertainty to define search radius
  ESTIMATOR_UNCERTAINTY_THRESHOLD: 1000.0
  # ORB feature matching parameters
  ORB_NFEATURES: 500
  ORB_MIN_MATCH_COUNT: 30  # Minimum matches for reliable detection
  RANSAC_REPROJECTION_THRESHOLD: 10.0  # RANSAC reprojection threshold

# ==============================================================================
# Tracking Configuration
# ==============================================================================
Tracking:
  # Default tracking algorithm: 'CSRT', 'ParticleFilter', etc.
  DEFAULT_TRACKING_ALGORITHM: CSRT
  # Visualization settings
  TRACKING_RECTANGLE_COLOR: [255, 0, 0]
  CENTER_CIRCLE_COLOR: [0, 255, 0]
  CENTER_HISTORY_LENGTH: 10
  # Displacement threshold (as a fraction of frame dimensions)
  MAX_DISPLACEMENT_THRESHOLD: 0.25
  # Tracking failure timeout before attempting redetection (seconds)
  TRACKING_FAILURE_TIMEOUT: 5.0
  # CSRT tracker parameters (if using CSRT)
  CSRT_APPEARANCE_LEARNING_RATE: 0.05
  # Appearance validation parameters
  APPEARANCE_THRESHOLD: 0.3  # Similarity threshold between 0 and 1
  APPEARANCE_CONFIDENCE_THRESHOLD: 0.5
  # Confidence weights
  MOTION_CONFIDENCE_WEIGHT: 0.5
  APPEARANCE_CONFIDENCE_WEIGHT: 0.5
  # Confidence threshold for accepting tracking result
  CONFIDENCE_THRESHOLD: 0.6
  # Re-detection mechanism
  REDETECTION_ATTEMPTS: 5
  # Particle Filter parameters (if using ParticleFilter)
  PF_NUM_PARTICLES: 500
  PF_INIT_POS_STD: 20.0  # Initial position standard deviation
  PF_INIT_VEL_STD: 5.0   # Initial velocity standard deviation
  PF_INIT_ACC_STD: 1.0   # Initial acceleration standard deviation
  PF_POS_STD: 15.0       # Process noise standard deviation for position
  PF_VEL_STD: 5.0        # Process noise standard deviation for velocity
  PF_ACC_STD: 1.0        # Process noise standard deviation for acceleration
  PF_APPEARANCE_LIKELIHOOD_SCALE: 25.0  # Scale factor for appearance likelihood
  PF_APPEARANCE_LEARNING_RATE: 0.05     # Learning rate for adaptive appearance model
  PF_COLOR_WEIGHT: 0.7   # Weight for color histogram similarity
  PF_EDGE_WEIGHT: 0.3    # Weight for edge-based similarity
  PF_CANNY_THRESHOLD1: 50
  PF_CANNY_THRESHOLD2: 150
  PF_EFFECTIVE_PARTICLE_NUM_THRESHOLD: 0.5  # Ratio of PF_NUM_PARTICLES
  PF_RANDOM_PARTICLE_RATIO: 0.1  # Ratio of particles to reinitialize randomly

# ==============================================================================
# Follower Configuration
# ==============================================================================
Follower:
  # MAVLink interface settings
  USE_MAVLINK2REST: true
  FOLLOWER_DATA_REFRESH_RATE: 5
  # ROI selection mode
  ROI_SELECTION_MODE: MANUAL
  # Visualization settings
  SHOW_TRACKING_WINDOW: true
  DISPLAY_DEVIATIONS: false
  TRACKED_BBOX_STYLE: fancy
  FOLLOWER_ACTIVE_COLOR: [0, 0, 255]
  FOLLOWER_INACTIVE_COLOR: [0, 255, 255]
  BBOX_LINE_THICKNESS: 2
  EXTENDED_LINE_THICKNESS: 2
  CORNER_DOT_RADIUS: 4
  CROSSHAIR_ARM_LENGTH: 20
  BBOX_CORNER_ARM_LENGTH: 20
  OVERLAY_OPACITY: 128
  # Follower mode options: 'ground_view', 'constant_distance', 'constant_position', 'chase_follower', etc.
  FOLLOWER_MODE: chase_follower
  # Control settings
  ENABLE_ALTITUDE_CONTROL: true
  TARGET_POSITION_MODE: center

# ==============================================================================
# Yaw Control Parameters
# ==============================================================================
YawControl:
  ENABLE_YAW_CONTROL: false
  YAW_CONTROL_THRESHOLD: 0.3
  YAW_LATERAL_BLEND_FACTOR: 0.5
  YAW_DEAD_ZONE: 0.2

# ==============================================================================
# Vertical Error Recalculation Parameters
# ==============================================================================
VerticalErrorRecalculation:
  VERTICAL_RECALC_DELAY: 0.1
  YAW_PITCH_SYNC_FACTOR: 0.5

# ==============================================================================
# Gimbal Configuration
# ==============================================================================
Gimbal:
  ENABLE_GIMBAL_PRIORITY: true

# ==============================================================================
# Adaptive Control Configuration
# ==============================================================================
AdaptiveControl:
  ADAPTIVE_YAW_CONTROL: false

# ==============================================================================
# Chase Follower Rate Limits Configuration
# ==============================================================================
ChaseFollower:
  MAX_ROLL_RATE: 20.0
  MAX_PITCH_RATE: 10.0
  MAX_YAW_RATE: 10.0
  MAX_THRUST: 1.0
  MIN_THRUST: 0.3
  MIN_GROUND_SPEED: 0
  MAX_GROUND_SPEED: 100
  TARGET_SPEED: 60
  MAX_BANK_ANGLE: 20
  YAW_ERROR_CHECK_ENABLED: true
  YAW_ERROR_THRESHOLD: 20
  ALTITUDE_FAILSAFE_ENABLED: false

# ==============================================================================
# Control and PID Parameters
# ==============================================================================
PID:
  PID_GAINS:
    x: {p: 4.5, i: 0.1, d: 1.5}
    y: {p: 4.5, i: 0.1, d: 1.5}
    z: {p: 2, i: 0.03, d: 0.05}
    roll_rate: {p: 1, i: 0.05, d: 0.2}
    pitch_rate: {p: 20, i: 0.1, d: 0.4}
    yaw_rate: {p: 2.7, i: 0.1, d: 0.01}
    thrust: {p: 0.1, i: 3, d: 1}
  PROPORTIONAL_ON_MEASUREMENT: false
  ENABLE_ANTI_WINDUP: true
  ANTI_WINDUP_BACK_CALC_COEFF: 0.1

# ==============================================================================
# Velocity and Descent Limits Configuration
# ==============================================================================
VelocityDescent:
  VELOCITY_LIMITS:
    x: 10.0
    y: 10.0
    z: 5.0
  ENABLE_DESCEND_TO_TARGET: false
  MIN_DESCENT_HEIGHT: 40
  MAX_CLIMB_HEIGHT: 10000
  MAX_RATE_OF_DESCENT: 2
  MAX_YAW_RATE: 10
  DESIRE_AIM: [0, 0]
  IS_CAMERA_GIMBALED: false
  BASE_ADJUSTMENT_FACTOR_X: 0.1
  BASE_ADJUSTMENT_FACTOR_Y: 0.1
  ALTITUDE_FACTOR: 0.005

# ==============================================================================
# Gain Scheduling Configuration
# ==============================================================================
GainScheduling:
  ENABLE_GAIN_SCHEDULING: false
  GAIN_SCHEDULING_PARAMETER: current_altitude
  ALTITUDE_GAIN_SCHEDULE:
    '(0, 20)':
      x: {p: 5.5, i: 0.2, d: 0.4}
      y: {p: 5.5, i: 0.2, d: 0.4}
      z: {p: 1, i: 0.01, d: 0.1}
    '(20, 50)':
      x: {p: 6, i: 0.25, d: 0.5}
      y: {p: 6, i: 0.25, d: 0.5}
      z: {p: 1, i: 0.015, d: 0.15}
    '(50, 100)':
      x: {p: 6.5, i: 0.3, d: 0.6}
      y: {p: 6.5, i: 0.3, d: 0.6}
      z: {p: 1, i: 0.02, d: 0.2}
    '(100, 150)':
      x: {p: 6, i: 0.3, d: 1.0}
      y: {p: 6, i: 0.3, d: 1.0}
      z: {p: 1, i: 0.01, d: 0.01}
    '(150, 200)':
      x: {p: 5.5, i: 0.25, d: 0.8}
      y: {p: 5.5, i: 0.25, d: 0.8}
      z: {p: 1, i: 0.01, d: 0.05}

# ==============================================================================
# Setpoint Configuration
# ==============================================================================
Setpoint:
  CAMERA_YAW_OFFSET: 0
  SETPOINT_PUBLISH_RATE_S: 0.1
  ENABLE_SETPOINT_DEBUGGING: false

# ==============================================================================
# Debugging and Logging
# ==============================================================================
Debugging:
  ENABLE_DEBUGGING: true
  LOG_FILE_PATH: logs/tracking_log.txt

# ==============================================================================
# GStreamer Configuration
# ==============================================================================
GStreamer:
  ENABLE_GSTREAMER_STREAM: false
  GSTREAMER_HOST: 127.0.0.1
  GSTREAMER_PORT: 2000
  GSTREAMER_BITRATE: 2000
  GSTREAMER_WIDTH: 1280
  GSTREAMER_HEIGHT: 720
  GSTREAMER_FRAMERATE: 15
  GSTREAMER_BUFFER_SIZE: 50000000
  GSTREAMER_SPEED_PRESET: ultrafast
  GSTREAMER_KEY_INT_MAX: 30
  GSTREAMER_TUNE: zerolatency
  GSTREAMER_CONTRAST: 5.0
  GSTREAMER_BRIGHTNESS: 10
  GSTREAMER_SATURATION: 5
# ==============================================================================
# MAVLink Configuration
# ==============================================================================
MAVLink:
  MAVLINK_ENABLED: true
  MAVLINK_HOST: 127.0.0.1 #For WSL:172.21.148.30 (your WSL IP).  For real companion computer set to 127.0.0.1
  MAVLINK_PORT: 8088
  MAVLINK_POLLING_INTERVAL: 0.5
  MAVLINK_DATA_POINTS:
    latitude: /vehicles/1/components/1/messages/GLOBAL_POSITION_INT/message/lat
    longitude: /vehicles/1/components/1/messages/GLOBAL_POSITION_INT/message/lon
    altitude_msl: /vehicles/1/components/1/messages/ALTITUDE/message/altitude_amsl
    altitude_agl: /vehicles/1/components/1/messages/ALTITUDE/message/altitude_relative
    voltage: /vehicles/1/components/1/messages/SYS_STATUS/message/voltage_battery
    airspeed: /vehicles/1/components/1/messages/VFR_HUD/message/airspeed
    throttle: /vehicles/1/components/1/messages/VFR_HUD/message/throttle
    groundspeed: /vehicles/1/components/1/messages/VFR_HUD/message/groundspeed
    climb: /vehicles/1/components/1/messages/VFR_HUD/message/climb
    vn: /vehicles/1/components/1/messages/LOCAL_POSITION_NED/message/vx
    ve: /vehicles/1/components/1/messages/LOCAL_POSITION_NED/message/vy
    vd: /vehicles/1/components/1/messages/LOCAL_POSITION_NED/message/vz
    flight_path_angle: null
    roll: /vehicles/1/components/1/messages/ATTITUDE/message/roll
    pitch: /vehicles/1/components/1/messages/ATTITUDE/message/pitch
    heading: /vehicles/1/components/1/messages/VFR_HUD/message/heading
    vdop: /vehicles/1/components/1/messages/GPS_RAW_INT/message/vdop
    hdop: /vehicles/1/components/1/messages/GPS_RAW_INT/message/hdop
    satellites_visible: /vehicles/1/components/1/messages/GPS_RAW_INT/message/satellites_visible
    flight_mode: /vehicles/1/components/1/messages/HEARTBEAT/message/custom_mode
    arm_status: /vehicles/1/components/1/messages/HEARTBEAT/message/base_mode

# OSD Configuration
OSD:
  OSD_ENABLED: true
  OSD_CONFIG:
    name:
      enabled: true
      text: PixEagle
      position: [3, 5]
      color: [255, 255, 255]
      font_size: 0.7
    datetime:
      enabled: true
      position: [98, 5]
      color: [255, 255, 255]
      font_size: 0.6
      alignment: right
    crosshair:
      enabled: true
      color: [0, 255, 0]
      thickness: 2
      length: 15
    attitude_indicator:
      enabled: true
      position: [50, 50]
      size: [70, 70]
      horizon_color: [255, 255, 255]
      grid_color: [200, 200, 200]
      thickness: 2
    mavlink_data:
      enabled: true
      fields:
        heading:
          position: [45, 30]
          font_size: 0.5
          color: [255, 255, 255]
        airspeed:
          position: [10, 45]
          font_size: 0.4
          color: [255, 255, 255]
        groundspeed:
          position: [10, 55]
          font_size: 0.4
          color: [255, 255, 255]
        throttle:
          position: [10, 65]
          font_size: 0.3
          color: [255, 255, 255]
        altitude_msl:
          position: [65, 45]
          font_size: 0.4
          color: [255, 255, 255]
        altitude_agl:
          position: [65, 55]
          font_size: 0.4
          color: [255, 255, 255]
        flight_path_angle:
          position: [65, 65]
          font_size: 0.4
          color: [255, 255, 255]
        roll:
          position: [45, 75]
          font_size: 0.5
          color: [255, 255, 255]
        pitch:
          position: [45, 80]
          font_size: 0.5
          color: [255, 255, 255]
        latitude:
          position: [2, 92]
          font_size: 0.3
          color: [255, 255, 255]
        longitude:
          position: [2, 96]
          font_size: 0.3
          color: [255, 255, 255]
        satellites_visible:
          position: [2, 88]
          font_size: 0.4
          color: [255, 255, 255]
        hdop:
          position: [2, 84]
          font_size: 0.4
          color: [255, 255, 255]
        voltage:
          position: [2, 12]
          font_size: 0.4
          color: [255, 255, 255]
        arm_status:
          position: [2, 16]
          font_size: 0.5
          color: [255, 255, 255]
        flight_mode:
          position: [45, 10]
          font_size: 0.5
          color: [0, 0, 255]
          alignment: center
    tracker_status:
      enabled: true
      position: [75, 92]
      font_size: 0.4
      color: [255, 255, 0]
    follower_status:
      enabled: true
      position: [75, 96]
      font_size: 0.4
      color: [255, 255, 0]
